Repository spring-cloud/spring-cloud-build, pull requests merged in 2021-07, with the labels that each got.

#213 Updating asciidoctorJ versions, handling deprecated constructors, removing unused import
  docs/src/main/java/org/springframework/cloud/internal/asciidoctor/ReadmeMain.java
  docs/src/test/java/org/springframework/cloud/internal/asciidoctor/ReadmeMainTests.java
  pom.xml
Labels: enhancement

#214 Replace symlink with include
  docs/src/main/asciidoc/index.adoc
Labels: documentation, in progress

#215 Bumped versions of libs
  .mvn/maven.config
  pom.xml
Labels: dependencies
